// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgeyOOX2DO4x_C8PqHhHHXvjL_ykoc6dM',
    appId: '1:320074066076:web:93a08a3a1d562c8384e559',
    messagingSenderId: '320074066076',
    projectId: 'challengerapp-9ca54',
    authDomain: 'challengerapp-9ca54.firebaseapp.com',
    storageBucket: 'challengerapp-9ca54.appspot.com',
    measurementId: 'G-QWY45WX3ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP7lk-Tdez3rlNUFo5jAcDVL8QgEINuAc',
    appId: '1:320074066076:android:09089412d8c662ed84e559',
    messagingSenderId: '320074066076',
    projectId: 'challengerapp-9ca54',
    storageBucket: 'challengerapp-9ca54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSNSce3broTxuiZ5HGdOLmOx5QP3YUjdA',
    appId: '1:320074066076:ios:f3c497ce19b1516084e559',
    messagingSenderId: '320074066076',
    projectId: 'challengerapp-9ca54',
    storageBucket: 'challengerapp-9ca54.appspot.com',
    iosClientId: '320074066076-7k2qtaie6qmlb5ombemdth9la3nikscg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSNSce3broTxuiZ5HGdOLmOx5QP3YUjdA',
    appId: '1:320074066076:ios:dd21a2558a84a3d584e559',
    messagingSenderId: '320074066076',
    projectId: 'challengerapp-9ca54',
    storageBucket: 'challengerapp-9ca54.appspot.com',
    iosClientId: '320074066076-uctlljbkt5dputa44m83bsf60fjblem8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallengerApp.RunnerTests',
  );
}
